name: default
fullyQualifiedName: testUnity.demo.default
dataProducts: []
owners: []
service:
  id: 686dc5da-a770-4d95-92be-34544ad38d95
  type: databaseService
  name: testUnity
  fullyQualifiedName: testUnity
  description: ""
  displayName: testUnity
  deleted: false
serviceType: UnityCatalog
database:
  id: be64a4f3-8bae-40fa-b446-404134c794ec
  type: database
  name: demo
  fullyQualifiedName: testUnity.demo
  displayName: demo
  deleted: false
tables:
  - id: 1c942229-1ebc-4ac0-b8e0-c61b4ebf4fc8
    type: table
    name: complex_data
    fullyQualifiedName: testUnity.demo.default.complex_data
    displayName: complex_data
    deleted: false
  - id: 33b6e039-468c-4093-b6c8-49956dd1d697
    type: table
    name: demo_data
    fullyQualifiedName: testUnity.demo.default.demo_data
    displayName: demo_data
    deleted: false
  - id: d3e2a0fc-39aa-4ffb-abf9-0152acbb5e08
    type: table
    name: demo_data_ext_tbl2
    fullyQualifiedName: testUnity.demo.default.demo_data_ext_tbl2
    displayName: demo_data_ext_tbl2
    deleted: false
  - id: c432addf-b579-4010-a4a7-3a89cda53fc6
    type: table
    name: demo_data_ext_tbl3
    fullyQualifiedName: testUnity.demo.default.demo_data_ext_tbl3
    displayName: demo_data_ext_tbl3
    deleted: false
  - id: 0a1450bc-eb2a-4139-b746-403d9b761f49
    type: table
    name: example_table
    fullyQualifiedName: testUnity.demo.default.example_table
    displayName: example_table
    deleted: false
  - id: 5387129d-842c-4214-ba35-afa78553262b
    type: table
    name: load_data_exp
    fullyQualifiedName: testUnity.demo.default.load_data_exp
    displayName: load_data_exp
    deleted: false
tags: []
domains: []
sourceHash: c9c4eaaa37bf598002abd85a49d4f6a9
entityStatus: Approved
