name: default
fullyQualifiedName: large_file_datalake_local2.default
dataProducts: []
tags: []
owners: []
service:
  id: ecc2804c-4a2f-4a1a-98de-1e1d8e10c6ed
  type: databaseService
  name: large_file_datalake_local2
  fullyQualifiedName: large_file_datalake_local2
  displayName: large_file_datalake_local2
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 96ce7314-9107-44a1-9a82-9a8583649fee
    type: databaseSchema
    name: partitioned-data-container
    fullyQualifiedName: large_file_datalake_local2.default.partitioned-data-container
    displayName: partitioned-data-container
    deleted: false
default: false
domains: []
sourceHash: 950f826502f13c66429644194b585cc9
entityStatus: Unprocessed
