name: Product Master
fullyQualifiedName: Product Master
displayName: Product Master
description: All Product Master Attributes for everyone's consumption
style:
  color: "#0968da"
owners: []
experts: []
reviewers: []
domains:
  - id: 9545569e-9b4e-4be0-8142-ce5d502fbab7
    type: domain
    name: Product
    fullyQualifiedName: Product
    description: A Domain producing  and serving Product Master Data.
    displayName: Product Name
lifecycleStage: DEVELOPMENT
tags: []
entityStatus: Approved
