name: default
fullyQualifiedName: datalake large files testing s3.default
dataProducts: []
tags: []
owners: []
service:
  id: 1260697d-6d10-4b82-b4a6-ca95bab8c257
  type: databaseService
  name: datalake large files testing s3
  fullyQualifiedName: datalake large files testing s3
  description: ""
  displayName: datalake large files testing s3
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 8b75062b-09a4-4ae9-b8cc-c79f836677d8
    type: databaseSchema
    name: amazon-sagemaker-654654515160-us-east-2-6ptx16hel6xajt
    fullyQualifiedName: datalake large files testing s3.default.amazon-sagemaker-654654515160-us-east-2-6ptx16hel6xajt
    displayName: amazon-sagemaker-654654515160-us-east-2-6ptx16hel6xajt
    deleted: false
  - id: 450c97f7-1975-4863-8db3-a562c30250a3
    type: databaseSchema
    name: argo-workflows-fiwfyjol
    fullyQualifiedName: datalake large files testing s3.default.argo-workflows-fiwfyjol
    displayName: argo-workflows-fiwfyjol
    deleted: false
  - id: ffbfda3c-c7a3-4b63-b7d4-b79781dfd3f1
    type: databaseSchema
    name: argo-workflows-sandbox-mnsyacxp
    fullyQualifiedName: datalake large files testing s3.default.argo-workflows-sandbox-mnsyacxp
    displayName: argo-workflows-sandbox-mnsyacxp
    deleted: false
  - id: 40a2c2a5-fcf0-475a-b6be-2bf1190b3b55
    type: databaseSchema
    name: athena-query-results-654654515160-us-east-2
    fullyQualifiedName: datalake large files testing s3.default.athena-query-results-654654515160-us-east-2
    displayName: athena-query-results-654654515160-us-east-2
    deleted: false
  - id: e84d9f77-fb5d-4a50-9940-d98fe8445fcf
    type: databaseSchema
    name: cl-performance-test
    fullyQualifiedName: datalake large files testing s3.default.cl-performance-test
    displayName: cl-performance-test
    deleted: false
  - id: 8bdf5c38-51e7-4c16-ac08-a4af1211cf6b
    type: databaseSchema
    name: collate-athena-654654515160
    fullyQualifiedName: datalake large files testing s3.default.collate-athena-654654515160
    displayName: collate-athena-654654515160
    deleted: false
  - id: 53a0628c-f31e-43f3-b4cb-2f28f078a2cb
    type: databaseSchema
    name: collate-glue-connector-test
    fullyQualifiedName: datalake large files testing s3.default.collate-glue-connector-test
    displayName: collate-glue-connector-test
    deleted: false
  - id: 2d6fd81f-dc71-4ab9-84c5-69aae64175ab
    type: databaseSchema
    name: collate-landing-zone-beta
    fullyQualifiedName: datalake large files testing s3.default.collate-landing-zone-beta
    displayName: collate-landing-zone-beta
    deleted: false
  - id: 146d9b65-1e90-4702-9540-0100cee0a0f8
    type: databaseSchema
    name: collate-landing-zone-beta-dump
    fullyQualifiedName: datalake large files testing s3.default.collate-landing-zone-beta-dump
    displayName: collate-landing-zone-beta-dump
    deleted: false
  - id: ceabe01b-11e8-4eaa-8cc1-14cb63ff1b96
    type: databaseSchema
    name: collate-s3-connector-test-bucket
    fullyQualifiedName: datalake large files testing s3.default.collate-s3-connector-test-bucket
    displayName: collate-s3-connector-test-bucket
    deleted: false
  - id: 8d1b05b3-8e6f-475e-8d4b-3db2ad23b5d5
    type: databaseSchema
    name: datalake-all-filetypes
    fullyQualifiedName: datalake large files testing s3.default.datalake-all-filetypes
    displayName: datalake-all-filetypes
    deleted: false
  - id: 9ed82293-e211-4e3f-98e7-7d67b3e3e113
    type: databaseSchema
    name: om-demo-datalake
    fullyQualifiedName: datalake large files testing s3.default.om-demo-datalake
    displayName: om-demo-datalake
    deleted: false
  - id: d80f887c-2105-4a0a-9e01-08ee848a11d7
    type: databaseSchema
    name: om-pipeline-logs-prod
    fullyQualifiedName: datalake large files testing s3.default.om-pipeline-logs-prod
    displayName: om-pipeline-logs-prod
    deleted: false
  - id: da24da0f-e936-4068-868d-6e2dd39611f3
    type: databaseSchema
    name: om-sample-demo
    fullyQualifiedName: datalake large files testing s3.default.om-sample-demo
    displayName: om-sample-demo
    deleted: false
  - id: 11f03b74-4760-4d69-8df8-8706b608fbd3
    type: databaseSchema
    name: openmetadata-rpwawibh
    fullyQualifiedName: datalake large files testing s3.default.openmetadata-rpwawibh
    displayName: openmetadata-rpwawibh
    deleted: false
  - id: 00ad946f-f7ea-43c7-aef6-7f25418092c4
    type: databaseSchema
    name: python-sdk-resources
    fullyQualifiedName: datalake large files testing s3.default.python-sdk-resources
    displayName: python-sdk-resources
    deleted: false
  - id: 075a4fb2-c9b6-4b15-80ea-3dc0883c5612
    type: databaseSchema
    name: quicksight-s3-collate
    fullyQualifiedName: datalake large files testing s3.default.quicksight-s3-collate
    displayName: quicksight-s3-collate
    deleted: false
  - id: ef13b3c5-6009-414a-9a1c-f6e8815151af
    type: databaseSchema
    name: redshift-serverless-mt-bucket
    fullyQualifiedName: datalake large files testing s3.default.redshift-serverless-mt-bucket
    displayName: redshift-serverless-mt-bucket
    deleted: false
  - id: 603c0bde-8998-4862-a34f-59ff9cb5b49f
    type: databaseSchema
    name: snowflake-external-table-bucket
    fullyQualifiedName: datalake large files testing s3.default.snowflake-external-table-bucket
    displayName: snowflake-external-table-bucket
    deleted: false
  - id: 8990a580-0396-44e6-9d9a-83d68059b59c
    type: databaseSchema
    name: soc2-content
    fullyQualifiedName: datalake large files testing s3.default.soc2-content
    displayName: soc2-content
    deleted: false
  - id: b17a8b65-e0e8-434f-9b62-30709a057426
    type: databaseSchema
    name: test-firehose-con-bucket
    fullyQualifiedName: datalake large files testing s3.default.test-firehose-con-bucket
    displayName: test-firehose-con-bucket
    deleted: false
  - id: baf6d521-a938-489c-b601-2beb13ad877c
    type: databaseSchema
    name: test-uploads-20250305
    fullyQualifiedName: datalake large files testing s3.default.test-uploads-20250305
    displayName: test-uploads-20250305
    deleted: false
  - id: b38092fe-a18e-42f9-89df-c97b8387fbd7
    type: databaseSchema
    name: testdatalake-ingestion
    fullyQualifiedName: datalake large files testing s3.default.testdatalake-ingestion
    displayName: testdatalake-ingestion
    deleted: false
default: false
domains: []
sourceHash: e4f4bbd5eef0ad481437acb3ae0695d1
entityStatus: Unprocessed
