name: default
fullyQualifiedName: MysqlPlaywrightTest.default
dataProducts: []
tags: []
owners: []
service:
  id: 812b101d-0ea3-4abb-b51a-2526de3209e6
  type: databaseService
  name: MysqlPlaywrightTest
  fullyQualifiedName: MysqlPlaywrightTest
  description: ""
  displayName: MysqlPlaywrightTest
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: 4b20d34c-ba2c-4653-b80d-8b6524346426
    type: databaseSchema
    name: cypress_integrations_test_db
    fullyQualifiedName: MysqlPlaywrightTest.default.cypress_integrations_test_db
    displayName: cypress_integrations_test_db
    deleted: false
default: false
domains: []
sourceHash: a6271f4af4beb2ea28fbd9719c851c43
entityStatus: Approved
