name: default
fullyQualifiedName: large_file_datalake_local4.default
dataProducts: []
tags: []
owners: []
service:
  id: b68c352d-6eba-4cde-b381-166304c2a263
  type: databaseService
  name: large_file_datalake_local4
  fullyQualifiedName: large_file_datalake_local4
  displayName: large_file_datalake_local4
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: b9b062b8-3fe7-434a-a5b9-93ff16d0aa7b
    type: databaseSchema
    name: partitioned-data-container
    fullyQualifiedName: large_file_datalake_local4.default.partitioned-data-container
    displayName: partitioned-data-container
    deleted: false
default: false
domains: []
sourceHash: 86c3a1e828c48c43125a2414f6de1999
entityStatus: Unprocessed
