name: default
fullyQualifiedName: GyoTestLocal.default
dataProducts: []
tags: []
owners: []
service:
  id: fc33c634-c86c-4744-b5b9-31265788cd04
  type: databaseService
  name: GyoTestLocal
  fullyQualifiedName: GyoTestLocal
  description: ""
  displayName: GyoTestLocal
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: 70b46c0f-18fc-4f19-964e-e546d2b34dc5
    type: databaseSchema
    name: information_schema
    fullyQualifiedName: GyoTestLocal.default.information_schema
    displayName: information_schema
    deleted: false
  - id: f48d00b8-dd4f-4116-89d1-04aefa5bb9b5
    type: databaseSchema
    name: openmetadata_db
    fullyQualifiedName: GyoTestLocal.default.openmetadata_db
    displayName: openmetadata_db
    deleted: false
default: false
domains: []
sourceHash: 4e89e4bb511b96ac60ba10b949badac7
entityStatus: Approved
