name: default
fullyQualifiedName: abc.default
dataProducts: []
tags: []
owners: []
service:
  id: d9609609-83c5-46dc-b2a7-ea2b261be6d7
  type: databaseService
  name: abc
  fullyQualifiedName: abc
  description: ""
  displayName: abc
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: b7bb62d9-5ce4-4da8-a0bd-56aa291fb4f9
    type: databaseSchema
    name: awsdatalake-testing
    fullyQualifiedName: abc.default.awsdatalake-testing
    displayName: awsdatalake-testing
    deleted: false
default: false
domains: []
sourceHash: af2d10ae501ee7c3d3a5bed39212bb4a
entityStatus: Unprocessed
