name: default
fullyQualifiedName: testDbxtest.xto-us-12_veh-slv.default
description: Default schema (auto-created)
dataProducts: []
owners: []
service:
  id: d155115f-1a6b-479d-ac0c-96c07737c3a8
  type: databaseService
  name: testDbxtest
  fullyQualifiedName: testDbxtest
  description: ""
  displayName: testDbxtest
  deleted: false
serviceType: Databricks
database:
  id: 8e4137a1-38bf-4b6c-b8d4-891555cc6ea1
  type: database
  name: xto-us-12_veh-slv
  fullyQualifiedName: testDbxtest.xto-us-12_veh-slv
  displayName: xto-us-12_veh-slv
  deleted: false
tables: []
tags: []
domains: []
sourceHash: b4993c0225b8b143bdb71460d612a60d
entityStatus: Approved
