name: products
fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products
tableType: Regular
columns:
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: description
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: price
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: float
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.price
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: stock_quantity
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.stock_quantity
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: created_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.created_at
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: updated_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver.products.updated_at
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 383db911-3492-4a2e-ba45-9d102332d366
  type: databaseSchema
  name: Silver
  fullyQualifiedName: bigquery 111.modified-leaf-330420.Silver
  description: ""
  displayName: Silver
  deleted: false
database:
  id: fb3a207a-4029-4635-817c-ad4bc5251bc7
  type: database
  name: modified-leaf-330420
  fullyQualifiedName: bigquery 111.modified-leaf-330420
  displayName: modified-leaf-330420
  deleted: false
service:
  id: c721902a-455f-433b-8bdc-958e82710043
  type: databaseService
  name: bigquery 111
  fullyQualifiedName: bigquery 111
  description: ""
  displayName: bigquery 111
  deleted: false
serviceType: BigQuery
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://console.cloud.google.com/bigquery?project=modified-leaf-330420&ws=!1m5!1m4!4m3!1smodified-leaf-330420!2sSilver!3sproducts
domains: []
dataProducts: []
lifeCycle:
  created:
    timestamp: 1721799589490
sourceHash: 61e33a0110700c328fbdd4086d8e81e4
processedLineage: false
entityStatus: Unprocessed
