name: product
fullyQualifiedName: DatabricksProd.main.sample_schema.product
description: "This table stores details about products, including their unique identifiers,\
  \ names, and age classifications. Users can leverage this data for inventory management,\
  \ product categorization, and sales analysis to enhance business decision-making."
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "A unique identifier for each product, used to distinguish one product\
      \ from another in the database."
    fullyQualifiedName: DatabricksProd.main.sample_schema.product.id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: "The name of the product, which serves as its primary label and is\
      \ used for identification and marketing purposes."
    fullyQualifiedName: DatabricksProd.main.sample_schema.product.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: age
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "The age of the product, which may indicate the duration since its\
      \ release or the target demographic for the product."
    fullyQualifiedName: DatabricksProd.main.sample_schema.product.age
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: e6488ef3-62f9-4597-80fb-624ea24adcfb
  type: databaseSchema
  name: sample_schema
  fullyQualifiedName: DatabricksProd.main.sample_schema
  displayName: sample_schema
  deleted: false
database:
  id: b0be8926-45aa-447c-adc4-e986fc49489f
  type: database
  name: main
  fullyQualifiedName: DatabricksProd.main
  displayName: main
  deleted: false
service:
  id: 70aba29d-0c08-4c85-9ee9-e60bc667f8c2
  type: databaseService
  name: DatabricksProd
  fullyQualifiedName: DatabricksProd
  displayName: databricksProD
  deleted: false
serviceType: Databricks
schemaDefinition: |-
  CREATE TABLE main.sample_schema.product (
    id INT,
    name STRING,
    age INT)
  USING delta
  TBLPROPERTIES (
    'delta.minReaderVersion' = '1',
    'delta.minWriterVersion' = '2')
tags:
  - tagFQN: imp.prod
    name: prod
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: columns.id.description
      newValue: "A unique identifier for each product, used to distinguish one product\
        \ from another in the database."
    - name: columns.name.description
      newValue: "The name of the product, which serves as its primary label and is\
        \ used for identification and marketing purposes."
    - name: columns.age.description
      newValue: "The age of the product, which may indicate the duration since its\
        \ release or the target demographic for the product."
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.2
  changeSummary:
    description:
      changedBy: ingestion-bot
      changedAt: 1743770529126
    columns.id.description:
      changedBy: ingestion-bot
      changedAt: 1743770529471
    columns.age.description:
      changedBy: ingestion-bot
      changedAt: 1743770529471
    columns.name.description:
      changedBy: ingestion-bot
      changedAt: 1743770529471
domains: []
dataProducts: []
sourceHash: 00f03a9f4042e87d475a2bc38418c1cc
processedLineage: false
entityStatus: Approved
