name: parameters
fullyQualifiedName: DatabricksProd.main.information_schema.parameters
description: Describes parameters of routines (functions) in the catalog.
tableType: View
columns:
  - name: specific_catalog
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Catalog containing the routine.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.specific_catalog
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: specific_schema
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Database (schema) containing the routine.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.specific_schema
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: specific_name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Schema unique (specific) name of the routine.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.specific_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: ordinal_position
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: The position (1-based) of the parameter in the routine parameter
      list.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.ordinal_position
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: parameter_mode
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Always 'IN'. Reserved for future use.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.parameter_mode
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: is_result
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Always 'NO'. Reserved for future use.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.is_result
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: as_locator
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: Always 'NO'. Reserved for future use.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.as_locator
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: parameter_name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: "Name of the parameters, NULL if unnamed."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.parameter_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: data_type
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: The parameter data type name.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.data_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: full_data_type
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: "The parameter data type definition, for example 'DECIMAL(10, 4)'."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.full_data_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: character_maximum_length
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    description: "Always NULL, reserved for future use."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.character_maximum_length
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: character_octet_length
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    description: "Always NULL, reserved for future use."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.character_octet_length
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: numeric_precision
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "For base-2 integral numeric types, FLOAT, and DOUBLE, the number\
      \ of supported bits. For DECIMAL the number of digits, NULL otherwise."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.numeric_precision
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: numeric_precision_radix
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "For DECIMAL 10, for all other numeric types 2, NULL otherwise."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.numeric_precision_radix
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: numeric_scale
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "For integral numeric types 0, for DECIMAL the number of digits to\
      \ the right of the decimal point, NULL otherwise."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.numeric_scale
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: datetime_precision
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "For DATE 0, for TIMESTAMP, and INTERVAL … SECOND 3, any other INTERVAL\
      \ 0, NULL otherwise."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.datetime_precision
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: interval_type
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: "For INTERVAL the unit portion of the interval, e.g. 'YEAR TO MONTH',\
      \ NULL otherwise."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.interval_type
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: interval_precision
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    description: "Always NULL, reserved for future use."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.interval_precision
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: maximum_cardinality
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    description: "Always NULL, reserved for future use."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.maximum_cardinality
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: parameter_default
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: "Always NULL, reserved for future use."
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.parameter_default
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: comment
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    description: An optional comment describing the parameter.
    fullyQualifiedName: DatabricksProd.main.information_schema.parameters.comment
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 7f351ab4-5b7d-4926-94be-fe250ba04d36
  type: databaseSchema
  name: information_schema
  fullyQualifiedName: DatabricksProd.main.information_schema
  displayName: information_schema
  deleted: false
database:
  id: b0be8926-45aa-447c-adc4-e986fc49489f
  type: database
  name: main
  fullyQualifiedName: DatabricksProd.main
  displayName: main
  deleted: false
service:
  id: 70aba29d-0c08-4c85-9ee9-e60bc667f8c2
  type: databaseService
  name: DatabricksProd
  fullyQualifiedName: DatabricksProd
  displayName: databricksProD
  deleted: false
serviceType: Databricks
schemaDefinition: ""
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 07841cf9fced463144f05310ad7e5986
processedLineage: false
entityStatus: Approved
