name: default
fullyQualifiedName: large_file_datalake_local3.default
dataProducts: []
tags: []
owners: []
service:
  id: 3a5d691b-6275-4bfb-ae8e-98ee9d7197de
  type: databaseService
  name: large_file_datalake_local3
  fullyQualifiedName: large_file_datalake_local3
  displayName: large_file_datalake_local3
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 44357991-41c6-48f6-b86f-ebddabdbe54f
    type: databaseSchema
    name: partitioned-data-container
    fullyQualifiedName: large_file_datalake_local3.default.partitioned-data-container
    displayName: partitioned-data-container
    deleted: false
default: false
domains: []
sourceHash: 0a60aadc8bbeed292c45e36f1b4be2ca
entityStatus: Unprocessed
