name: dev
fullyQualifiedName: Another Hybrid Runner Redshift 2.dev
dataProducts: []
tags: []
owners: []
service:
  id: 1ad6636f-d986-4238-a799-5798fe2aaa87
  type: databaseService
  name: Another Hybrid Runner Redshift 2
  fullyQualifiedName: Another Hybrid Runner Redshift 2
  description: ""
  displayName: Another Hybrid Runner Redshift 2
  deleted: false
serviceType: Redshift
databaseSchemas:
  - id: 027762a3-6cb5-4bfd-ac5b-585cf0346079
    type: databaseSchema
    name: redshift_connector_testing
    fullyQualifiedName: Another Hybrid Runner Redshift 2.dev.redshift_connector_testing
    displayName: redshift_connector_testing
    deleted: false
default: false
domains: []
sourceHash: ecf846dfd8c0537b2a8172366879bb11
entityStatus: Unprocessed
