name: product_inventory
fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.product_inventory
tableType: Regular
columns:
  - name: inventory_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.product_inventory.inventory_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.product_inventory.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: quantity
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.product_inventory.quantity
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: warehouse
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.product_inventory.warehouse
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 0b39e8e4-9204-4cf9-891f-055fb3ba3a4d
  type: databaseSchema
  name: hk_test
  fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test
  description: ""
  displayName: hk_test
  deleted: false
database:
  id: e8162acb-4849-4bc9-9fb2-b5a980672d27
  type: database
  name: modified-leaf-330420
  fullyQualifiedName: qr_bq.modified-leaf-330420
  displayName: modified-leaf-330420
  deleted: false
service:
  id: b8883cdf-71e2-4756-8dd4-39b94818ffb0
  type: databaseService
  name: qr_bq
  fullyQualifiedName: qr_bq
  description: ""
  displayName: qr_bq
  deleted: false
serviceType: BigQuery
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: lifeCycle
      newValue: "{\"created\":{\"timestamp\":1763667175907}}"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
sourceUrl: https://console.cloud.google.com/bigquery?project=modified-leaf-330420&ws=!1m5!1m4!4m3!1smodified-leaf-330420!2shk_test!3sproduct_inventory
domains: []
dataProducts: []
lifeCycle:
  created:
    timestamp: 1763667175907
sourceHash: f44bf982fc8ff32213449b92e3a11dc0
processedLineage: false
entityStatus: Unprocessed
