name: products
fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products
tableType: Regular
columns:
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products.product_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: category
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products.category
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: price
    dataType: INT
    dataLength: 1
    dataTypeDisplay: numeric
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products.price
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: created_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test.products.created_at
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 0b39e8e4-9204-4cf9-891f-055fb3ba3a4d
  type: databaseSchema
  name: hk_test
  fullyQualifiedName: qr_bq.modified-leaf-330420.hk_test
  description: ""
  displayName: hk_test
  deleted: false
database:
  id: e8162acb-4849-4bc9-9fb2-b5a980672d27
  type: database
  name: modified-leaf-330420
  fullyQualifiedName: qr_bq.modified-leaf-330420
  displayName: modified-leaf-330420
  deleted: false
service:
  id: b8883cdf-71e2-4756-8dd4-39b94818ffb0
  type: databaseService
  name: qr_bq
  fullyQualifiedName: qr_bq
  description: ""
  displayName: qr_bq
  deleted: false
serviceType: BigQuery
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: lifeCycle
      newValue: "{\"created\":{\"timestamp\":1763667175324}}"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
  changeSummary: {}
sourceUrl: https://console.cloud.google.com/bigquery?project=modified-leaf-330420&ws=!1m5!1m4!4m3!1smodified-leaf-330420!2shk_test!3sproducts
domains: []
dataProducts: []
lifeCycle:
  created:
    timestamp: 1763667175324
sourceHash: d5960562758d77bd17d33a8f44a0dfc3
processedLineage: false
entityStatus: Unprocessed
