name: default
fullyQualifiedName: Hybrid QA - Collate Saas to Runner.default
dataProducts: []
tags: []
owners: []
service:
  id: f8680185-1568-4cd5-8dcf-bfd58080ff30
  type: databaseService
  name: Hybrid QA - Collate Saas to Runner
  fullyQualifiedName: Hybrid QA - Collate Saas to Runner
  description: ""
  displayName: Hybrid QA - Collate Saas to Runner
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: b1e70de0-676a-429a-8437-28e12500a444
    type: databaseSchema
    name: cypress_integrations_test_db
    fullyQualifiedName: Hybrid QA - Collate Saas to Runner.default.cypress_integrations_test_db
    displayName: cypress_integrations_test_db
    deleted: false
default: false
domains: []
sourceHash: 5298dc8de9a9d081819158fbc38ff5f1
entityStatus: Approved
