name: qr_bq
fullyQualifiedName: qr_bq
serviceType: BigQuery
description: ""
connection:
  config:
    type: BigQuery
    scheme: bigquery
    hostPort: bigquery.googleapis.com
    costPerTB: 6.25
    credentials:
      gcpConfig:
        type: service_account
        authUri: https://accounts.google.com/o/oauth2/auth
        clientId: 112732782865529894463
        tokenUri: https://oauth2.googleapis.com/token
        projectId: modified-leaf-330420
        privateKey: fernet:gAAAAABphcPC2TOY-SXf2OXFKX5Y592v3ZpWCd6uaWTObsXPAhZ6OQbOkwbb7pOZ6k9NpZOjkb6jpyqQGuJ6amVUXBY3hP2sixB81kmyNUWWwRB27XeFqnGSlqCMdMfxpdSmcfCyd2L-VMs7sVMhxwQIglL_Lrr0H195rvv9t8x7hCvVEuqt7gZ5MZ-GDdVbGlI8k8NHTBfF347Gj2zM17dB2y0TMaCOXzljTtOg02-qVks7Pla_aDWVG_B4UvgnXtosQYU3BnPWRW7aKKgVVKcAsBrmkjxFSE4iXEJClDPRVAcx9uQV2Eaw03UnqMYuBAdeIuBcqV3ucD_W76XpfwGu0GqglttXgyM80gRb-akUT5H77-ZghGDQDDZoSRVilDKrbpUjBZCEArlI6g9mUOIp5gOj3bNTc4WjDlx80cmjfjlgbqQ6TrNqXnGKwpiVb7mIhMOychBmEDt0P7RrNCJh6eL2_vieoXHXy4j1YY3p4waQhVPCHKrmq7N-DVS8sKNJCZvry4hntoPg92gL3a-Tl-aoYTaJOY6T93-LCtS_Jb435YlkynZG4Jx1h6AGLDeggZ8bguSSIS7gXw_mqQ5TwjnhnjO5FoJgyO1THgWGtPdp9cxqUNU1J2FGoe-Aa2FepTuJS3pHzCplLLZCJqsqPQ-Q5aX9J0NIui14ly5cnLqiJT21ktjPPf8dWBf8LFSpZrHwftD99qd2Y2y90u7xCfpn3d6A4RR1V1EVu3bsIoeoq1J_7MJU6Pcb8JX7Ee35VeT3OURbqrDmzY5D41MIdWgFRqgxjTfJHXg4hWu_56QwhVwiDBOTjEqaCLPwN3pa-IH94B9U9ZI5TJzagOcJ1YB_nyioygbZsdpi4JB-hCaE55Ss562a9z-65DouJhdawYVUTILd6O_Tat2Se9ITsdOqqXzVNNQWctQrws1REfISxcK5V6fMKD_msa9KSRF1qqPi0vrg1MCFJ082AUPF5wy4qO-v7Lqd1DbPzBiLgQNDMXCnxrk2Fq53ox6uIGkUlBFFDfY8st3g9lAHhz1b4rEWik9wz4N-g7UrCzB3hDDVla49R2AbfKteRykLfrH8HCkO46Nje3JGdD6ZjeYY_9OBH2Ibhdx-j_X3EnoPjUfrRhvhC9GlwpPF6kmdkmESgaUlAyOnJa3ODTkZSWQkU4SlnLMoBum7UfjNe2KupZTlDhSbUfkZh_PANVuGOJQy7HBsAE8Sw-RBGesgsaawxVg95XIrJMztifZxJuHk3_5qFJWisEmCpPDNo-FLMHYe66rrK_O7PhiVH387d-xuUdIr0qt0D-QU1XSiBZcmMZguQAbAiJk1fgKC2vg4IJjk7QBDfZ0n_EROhc9lBKMqAElLqNzy6RUKOVR91WDcx8vFP8EwKVEyzbQl55ExJrhizP4ysyDikXohk1rCsuG_bxo4o2GXWADQ2GYDKWRkpMzuABqB4qJERFd1bGwI0rjEYXAdJ9oWcFKW2h0jxT2z-6Yhn4i9CzKGtvsjWJU8n9Dx_GmDTt6NopSnXMbzrXLkr5TaolCgzHkXb0McsjYu-XG4tLfKb5Xq_N-iNG2_pAOeRdD7Z_kSPqr8Sbyal4sFAktT6V_Uhr-pC_DyekddqDhufB1i37ND3Bsb-zRKvROKX7yAjX9mVtnjatPLnAtMwSaYwL-qJw2ha2TYbYQ_nPKaloCrJmMg9ljsWfPLdQLTl7aKAPN5aEaeu_Tm_VmGfVs2Tw0LPgh4D1ogGgAeACT1yAKWJx8a22azZv32uqHzmQ-Zj4CUFR54tXZZB46xkLmatKk6QkFB6VoSb41wLsF_u_nKNolC-UDb_EbDsQTXCxt_hp6Llw1O_RlCygvvDaNzPYD3sPzlY_Qg50-ZtPP2O_ugmHLGcu6yXmRZDhvefxjcmHprA2_GcmQEjsVB64pwSf81XzAa5lIUm6nS1VLJBoQs4qs0FpbDGOlfwl-RNJPs66tRACO6YPoiuepdMHGF3viiuBh2XYSb0YuOeoIwL_9L6JbIwOzIs5C5S9GC4LX0d5hXF3teQdWbn6uGu3i9ob4WpdPcY_MCLWWJ2fkBcPdWvAihAIUWcB37k_vIHx1YD9i47OUess12pNHpU_zEdXrOZPxDog5kBb8lTy5GTiS--rEL_G4-BO7c-BE0s99KREPjW8LFGJJpp56wjxqsvb1sBZShDSlrbYUqXfRIBkk6aMYs24amiAY4O9JzDhKB7tuTbILqlhsw-qS9ob-CV5chGsNIIFK3Rn5Xv-ZUryLVPNUb_RCtabzT3LEtbHdDy3BRj61yoTbEgAZru-A1XS5JenPE7R37jgOloOOKkmjlbyKBwvtVhHQr4WsGQdFc-fE=
        clientEmail: test-openmetadata@modified-leaf-330420.iam.gserviceaccount.com
        privateKeyId: 29ea18f61a73e4820c61c48f0a112d45677a36ae
        clientX509CertUrl: https://www.googleapis.com/robot/v1/metadata/x509/test-openmetadata%40modified-leaf-330420.iam.gserviceaccount.com
        authProviderX509CertUrl: https://www.googleapis.com/oauth2/v1/certs
      gcpImpersonateServiceAccount:
        lifetime: 3600
    usageLocation: us
    billingProjectId: modified-leaf-330420
    supportsDataDiff: true
    supportsDatabase: true
    supportsProfiler: true
    taxonomyLocation: us
    includePolicyTags: true
    taxonomyProjectID: []
    tableFilterPattern:
      excludes: []
      includes: []
    schemaFilterPattern:
      excludes: []
      includes:
        - hk_test
    supportsQueryComment: true
    databaseFilterPattern:
      excludes: []
      includes: []
    supportsDBTExtraction: true
    supportsSystemProfile: false
    sampleDataStorageConfig:
      config:
        prefix: ""
        bucketName: ""
        overwriteData: true
        storageConfig:
          assumeRoleSessionName: OpenMetadataSession
        filePathPattern: "{service_name}/{database_name}/{database_schema_name}/{table_name}/sample_data.parquet"
    supportsUsageExtraction: true
    supportsLineageExtraction: true
    supportsMetadataExtraction: true
    supportsIncrementalMetadataExtraction: true
pipelines:
  - id: e68a37a1-5d49-4144-9570-134b0d3f9fb4
    type: ingestionPipeline
    name: 107a2469-16e1-4f72-b84a-14e15c1e4b1f
    fullyQualifiedName: qr_bq.107a2469-16e1-4f72-b84a-14e15c1e4b1f
    displayName: Usage Agent
    deleted: false
  - id: 0be46952-b124-461f-a4f2-689f0067a496
    type: ingestionPipeline
    name: 22101799-3d1a-468e-b4a7-a085e453370e
    fullyQualifiedName: qr_bq.22101799-3d1a-468e-b4a7-a085e453370e
    displayName: Metadata Agent
    deleted: false
  - id: 8ee259e7-1f14-4cf1-948a-aa15289fdf99
    type: ingestionPipeline
    name: abbdb55e-761a-4531-bc84-cadbb71dfc94
    fullyQualifiedName: qr_bq.abbdb55e-761a-4531-bc84-cadbb71dfc94
    displayName: Lineage Agent
    deleted: false
tags: []
owners:
  - id: d32d383f-071b-4aa8-8de7-241b3493453c
    type: user
    name: himanshu
    fullyQualifiedName: himanshu
    displayName: Himanshu Khairajani
    deleted: false
dataProducts: []
ingestionRunner:
  id: 80a7ac93-1869-4c7e-b220-f19e7c302abd
  type: ingestionRunner
