name: snowflake_demo
fullyQualifiedName: snowflake_demo
serviceType: Snowflake
description: Show me during the community meeting!
connection:
  config:
    role: ACCOUNTADMIN
    type: Snowflake
    scheme: snowflake
    account: FMFAHQK-GI58232
    password: fernet:gAAAAABphcPC4L76rh7l0M0IQkBKnC02XUqQjjTuRfQsjh7y4syhbbmpuvXBeShTXaOB9WWTHewctaB2AARugvTMw046V-n7oQ==
    username: testopenmetadata
    warehouse: COMPUTE_WH
    creditCost: 3.3
    privateKey: fernet:gAAAAABphcPCKwyOLE3ldOmrpvZYspmW5mLXOru6q4ptlT8FwrdWdG4oLh7CMM1Pvc_CbXnSx-xGRKdaz-c8_5si9WIEKHOXCOZlcj83chK7Qc_qXN7CZ8qBmjhIE2ZTDicpK8Z8_aTLTmX-FVjRidSLRQj7V5jwejyq1jXC6JaylHP_t1jltqBPxTIXflt61EBmVBzjuGMiYi_ifCuDjuts9j1V_ChuGtD-Kt2LAn-qaz09MgngIFy_eRVXoY8u4IVP2i1BsjQE4D7AHT_TYXcbcSYAnwgRJoSKJlWo9N-ifkznCD5FM_GaT5itm8A5AbGe3R5G6bbc7o5z3KvoTWJOpuykT2Z0Js9EoEALxE828NWCweBkCj8okoWB3Gwrv_-cEtJzmZmB3O-GDelJdJkHhDPdYRjvFx6-3DphFtXNn7T0_xCoSQpEunCtFc3ssl664uJ5UbRL7LwEKtqRQYZktEvnkQh7UgVzvI1YeNb9KKCNLjSHNVK_rUTciifZcJ94MCAQfNH1AYwxw62A2FcNwDfo42GvmigJYaxL_2Ia8uyT0pyeR07d1UlEJ637DJRNFbLY4omSwT34nXL2Y8wyQ6-rGxSDS7N9E7hcDr-1xWNk8quniB74GhWdlFOd-gYkZ4955TttkBp-sGK6zE3Vk4J-LRhtER9VTV42LkLd6rLKLaqjFPx7PAUo3u1LQ1SXPPvlSbAqBGG3uaItctjPaDn11d1JMLxHnzqwSA8JwDLdtK27WmjsGhN_Tx1SQWIaFAqz8efAqz3iEI950O-1Qv0vtXwwh0CXqTHAmU-GIgs5SbCqTrm2Dit38vbdWL19qMLdj40qdmRF6quPaXUTyJlVbCm_1cMvj3wX9Ulne0QDq2Cuozj8WvNajfyYJnOq5lg1v1jJwHxE4E8q_LgTJpMKidc34cMP-kps6EDvzdXvr2XAW36Qxuwx4wrQrK4j4le6aF1eCx-baF5hmpaN5eM-wHbTUguOTf3jLVC2hGZizel_qAvGcyoBzv2JvmKzAKbZKJGcWoDmgByovQ4MKIfNXr0MaC83GVCryYX5qdb9xPY_--u-ZpNNf45k4gDH5bCfQ_OkHF69HtcEsMD7rpyahZxeWtwDMKwwAZgdugQ-uL_38Xhm2XN02HUfDlmtzRRMhYn5wWc7E4kn7vwQeqPMgGQmDdKL739iWJB8i6eWKbVVln2e6OjVtl_lLtbCVapqCiVv7F6E6n9otC5uuUnBhSq4fFeS_kz6X2XtbS_uZCAANAvaY_oFVHjR6rLnhlXuNcnDI5J7wiCYUCbn1nSew1dHRNZsiVFcSiM7XiBgUPF5X5nT4v-O3CTj4jo6RqRJm44IJ9G2AqtnXUFoQPZRNEc1i5QD6WA6toIFF9v503f_gO2kRs2ahAZOLLKSnK5yV4mHjtJGG5QZ0XIMKn1M6kCoQPcpehX_sZ97NZLKIpCMCgQR7EwvGoUlcosPs6dz0JsH_fWJ_f71qwubp7ocoq9LETr092XnhA9ZonYggVd5cgy28__2DGy9ck42syKkWKcx944RqqsUN-C1BWV6P0JpA7vX_8kMQE-cRhG2i6WJxabC_ZdpGx43t2S_OahXioTgt_7tDwT_-VNOxr83QJczBGN6am6OpNmXtm4Ai-wSJc0ji9K5RvqXD3RAvT5W73N7Hwn7xyfEkJ44ZyrFtx70mml4bNveTFaGw6BvylTiulUE1wxjxcNtu-PnkNpfizY7S1FSauVoj0Vzu4ju5qhCd6QJazuXoiMjRAHocJKd1HzbPeDz6VOpduYIClW683NSgNeKatgEBdxVsHTne5byEE2CTnx7vfj_qq03seqjRk2OBgYzpxgP0vOpCLynBr6uTVltJ_tL7r5BOn5rTZwmywDCYE5tNtHb7iReq_g_ypDX-3o_6Tq7upRZpWjJ1PvLd7SKh16Ja1ijJ2KaL7KUEPTT19TmDBKRTHa3aVQb0qZighAYdEmuzW1qZDdNqiejT_-WXX3tEtrMN16jSspgFSgPPJ7lNStqcyLcjuwqlWhByjfVP7PpHt1EPoLHxjVS6bH33JXZDyH_tMv2bPpBH0iKDzZEv0P9LT0AAy0s2mX161dA7imHVDCkvDLmHN0ZkML0si45BkXixj_X1euLV96aC3cM3WXY15vRFiMbsZyxlUPLZsa9JXhhh_9iPWtoGzLzfpnjGpxwQoOXeHQpfOQikdv5lDDy6XdyFp-WBuUvfzc3ObZqwVzXfz5Yi70f-4jrcvWIIH0ODWVY40067KVpUVJFlhMOx7U3wWZGHOMrVoTByF8B9C6xkngHUtPXsyOVfKNLFVsFZYtCsgttTEStaE5Cl06874vG_So1AoHK4P8Weqqk_uoElibc45TZ81Uhc4EY4PgdrVFE42xh_uGX7tbpPRDzU3LCuId7hBDkHZa3GGSDOfTeQvlV4EoZ-hQGgzEOA2iIaUDXCToy02pqcuQapFfxlmtj9jx15SThJqPeAyNXHkWuseR7RUap3R6Bdc_45jAlj5r_ek_cE9ANtE4ta4nPEexhbxyVRcebIZZJDXmP_biU-N0XtDtb
    includeStages: false
    includeStreams: false
    supportsDataDiff: true
    supportsDatabase: true
    supportsProfiler: true
    accountUsageSchema: SNOWFLAKE.ACCOUNT_USAGE
    tableFilterPattern:
      excludes: []
      includes: []
    connectionArguments: {}
    schemaFilterPattern:
      excludes:
        - ^information_schema$
      includes: []
    snowflakeSourceHost: app.snowflake.com
    supportsQueryComment: true
    databaseFilterPattern:
      excludes:
        - ^snowflake$
      includes: []
    supportsDBTExtraction: true
    supportsSystemProfile: true
    clientSessionKeepAlive: false
    includeTransientTables: false
    sampleDataStorageConfig:
      config:
        prefix: ""
        bucketName: ""
        overwriteData: true
        storageConfig:
          assumeRoleSessionName: OpenMetadataSession
        filePathPattern: "{service_name}/{database_name}/{database_schema_name}/{table_name}/sample_data.parquet"
    supportsUsageExtraction: true
    supportsLineageExtraction: true
    supportsMetadataExtraction: true
    snowflakePrivatekeyPassphrase: fernet:gAAAAABphcPC6R3mWF-iN-g1Tnrhg4PyOvi2ET4AJLmoYMkx3YFFNwn9pridtke1zGE37CXz47X73ZA_ILBBp1rGUX1yhT4eUQ==
    supportsIncrementalMetadataExtraction: true
pipelines:
  - id: 7b83511a-cebd-4987-943f-13716de3d71e
    type: ingestionPipeline
    name: ba9c2cbc-9ed7-42db-9089-a66d1a49e983
    fullyQualifiedName: snowflake_demo.ba9c2cbc-9ed7-42db-9089-a66d1a49e983
    displayName: snowflake_demo_metadata_tN8kgp7f
    deleted: false
tags: []
owners:
  - id: 883fe858-06c3-4253-89c3-68ab59a517e4
    type: user
    name: pmbrull
    fullyQualifiedName: pmbrull
    displayName: Admin
    deleted: false
incrementalChangeDescription:
  fieldsAdded:
    - name: ingestionAgent
      newValue: '"9e0f555a-6661-4e34-97da-93d3eb09988f"'
  fieldsUpdated:
    - name: connection
      oldValue: '"old-encrypted-value"'
      newValue: '"new-encrypted-value"'
  fieldsDeleted: []
  previousVersion: 1.2
  changeSummary: {}
dataProducts: []
ingestionRunner:
  id: 9e0f555a-6661-4e34-97da-93d3eb09988f
  type: ingestionRunner
  name: hybrid-runner-argowf
  fullyQualifiedName: hybrid-runner-argowf
  deleted: false
  inherited: false
  href: https://sandbox-beta.open-metadata.org/v1/ingestionRunners/9e0f555a-6661-4e34-97da-93d3eb09988f
