name: default
fullyQualifiedName: datalake_testing.default
dataProducts: []
tags: []
owners: []
service:
  id: a3e8a23a-a96b-42c3-a29c-4dfc48985683
  type: databaseService
  name: datalake_testing
  fullyQualifiedName: datalake_testing
  description: ""
  displayName: datalake_testing
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 03826594-b233-4092-8844-328b037426ad
    type: databaseSchema
    name: awsdatalake-testing-v3
    fullyQualifiedName: datalake_testing.default.awsdatalake-testing-v3
    displayName: awsdatalake-testing-v3
    deleted: false
default: false
domains: []
sourceHash: 8fb0e9a461592842437ce79fdcec9f11
entityStatus: Unprocessed
