name: products
fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products
tableType: Regular
columns:
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: description
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: price
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: float
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.price
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: stock_quantity
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.stock_quantity
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: created_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.created_at
    tags:
      - tagFQN: General.DateTime
        name: DateTime
        description: Absolute or relative dates or periods or times smaller than a
          day.
        source: Classification
        labelType: Generated
        state: Suggested
        appliedAt: 1767969396000
        appliedBy: admin
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: updated_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze.products.updated_at
    tags:
      - tagFQN: General.DateTime
        name: DateTime
        description: Absolute or relative dates or periods or times smaller than a
          day.
        source: Classification
        labelType: Generated
        state: Suggested
        appliedAt: 1767969396000
        appliedBy: admin
      - tagFQN: PII.NonSensitive
        name: NonSensitive
        description: "PII which is easily accessible from public sources and can include\
          \ zip code, race, gender, and date of birth."
        style: {}
        source: Classification
        labelType: Generated
        state: Suggested
        reason: Chose PII.NonSensitive with a classification score of 0.93
        appliedAt: 1767969396000
        appliedBy: admin
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 7556127c-d10d-4bb5-8336-f1e01ac0cdd2
  type: databaseSchema
  name: Bronze
  fullyQualifiedName: query_runner_bq.modified-leaf-330420.Bronze
  description: New description
  displayName: Bronze
  deleted: false
database:
  id: ca8d273e-c526-40d5-be10-20f981830f2c
  type: database
  name: modified-leaf-330420
  fullyQualifiedName: query_runner_bq.modified-leaf-330420
  displayName: modified-leaf-330420
  deleted: false
service:
  id: 97732e10-864e-4a8b-b734-9d0bcceb11fa
  type: databaseService
  name: query_runner_bq
  fullyQualifiedName: query_runner_bq
  description: ""
  displayName: query_runner_bq
  deleted: false
serviceType: BigQuery
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded:
    - name: columns.created_at.tags
      newValue: "[{\"tagFQN\":\"General.DateTime\",\"name\":\"DateTime\",\"description\"\
        :\"Absolute or relative dates or periods or times smaller than a day.\",\"\
        source\":\"Classification\",\"labelType\":\"Generated\",\"state\":\"Suggested\"\
        }]"
    - name: columns.updated_at.tags
      newValue: "[{\"tagFQN\":\"General.DateTime\",\"name\":\"DateTime\",\"description\"\
        :\"Absolute or relative dates or periods or times smaller than a day.\",\"\
        source\":\"Classification\",\"labelType\":\"Generated\",\"state\":\"Suggested\"\
        },{\"tagFQN\":\"PII.NonSensitive\",\"name\":\"NonSensitive\",\"description\"\
        :\"PII which is easily accessible from public sources and can include zip\
        \ code, race, gender, and date of birth.\",\"style\":{},\"source\":\"Classification\"\
        ,\"labelType\":\"Generated\",\"state\":\"Suggested\",\"reason\":\"Chose PII.NonSensitive\
        \ with a classification score of 0.93\"}]"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.2
  changeSummary: {}
sourceUrl: https://console.cloud.google.com/bigquery?project=modified-leaf-330420&ws=!1m5!1m4!4m3!1smodified-leaf-330420!2sBronze!3sproducts
domains: []
dataProducts: []
lifeCycle:
  created:
    timestamp: 1721799224341
sourceHash: 88940ee137ce532c1d091926d4e39146
processedLineage: false
entityStatus: Unprocessed
