name: default
fullyQualifiedName: mySQLProfilerTesting.default
dataProducts: []
tags: []
owners: []
service:
  id: 97415374-1a91-4fe6-ac3a-d2430e9e98c7
  type: databaseService
  name: mySQLProfilerTesting
  fullyQualifiedName: mySQLProfilerTesting
  description: ""
  displayName: mySQLProfilerTesting
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: 2ccbe055-80e8-43d8-a17b-89b855877b42
    type: databaseSchema
    name: cypress_integrations_test_db
    fullyQualifiedName: mySQLProfilerTesting.default.cypress_integrations_test_db
    displayName: cypress_integrations_test_db
    deleted: false
default: false
domains: []
sourceHash: 08fd086e8ad56bd1cbff14f981e9ef94
entityStatus: Approved
