name: default
fullyQualifiedName: demo_salesforce.default
dataProducts: []
tags: []
owners: []
service:
  id: 57f210f2-9ada-4497-92d4-1ed4316d9dc4
  type: databaseService
  name: demo_salesforce
  fullyQualifiedName: demo_salesforce
  description: ""
  displayName: demo_salesforce
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: 577faa78-100e-43dc-87e4-cf005ab3440b
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: demo_salesforce.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: f7f66732aff6519e028f30a14b9ff82d
entityStatus: Approved
