name: Product2
fullyQualifiedName: local_salesforce.default.salesforce.Product2
description: Product
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Product ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: Name
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Product Name
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.Name
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: ProductCode
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: Product Code
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.ProductCode
    tags: []
    constraint: "NULL"
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: Description
    dataType: VARCHAR
    dataLength: 4000
    dataTypeDisplay: textarea
    description: Product Description
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.Description
    tags: []
    constraint: "NULL"
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: IsActive
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Active
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.IsActive
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: LastModifiedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Modified Date
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.LastModifiedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 8
    children: []
    customMetrics: []
  - name: LastModifiedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Last Modified By ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.LastModifiedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 9
    children: []
    customMetrics: []
  - name: SystemModstamp
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: System Modstamp
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.SystemModstamp
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 10
    children: []
    customMetrics: []
  - name: Family
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Product Family
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.Family
    tags: []
    constraint: "NULL"
    ordinalPosition: 11
    children: []
    customMetrics: []
  - name: ExternalDataSourceId
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: External Data Source ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.ExternalDataSourceId
    tags: []
    constraint: "NULL"
    ordinalPosition: 12
    children: []
    customMetrics: []
  - name: ExternalId
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: string
    description: External ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.ExternalId
    tags: []
    constraint: "NULL"
    ordinalPosition: 13
    children: []
    customMetrics: []
  - name: DisplayUrl
    dataType: VARCHAR
    dataLength: 1000
    dataTypeDisplay: url
    description: Display URL
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.DisplayUrl
    tags: []
    constraint: "NULL"
    ordinalPosition: 14
    children: []
    customMetrics: []
  - name: QuantityUnitOfMeasure
    dataType: UNKNOWN
    dataLength: 40
    dataTypeDisplay: picklist
    description: Quantity Unit Of Measure
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.QuantityUnitOfMeasure
    tags: []
    constraint: "NULL"
    ordinalPosition: 15
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 16
    children: []
    customMetrics: []
  - name: LastViewedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Viewed Date
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.LastViewedDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 17
    children: []
    customMetrics: []
  - name: LastReferencedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Last Referenced Date
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.LastReferencedDate
    tags: []
    constraint: "NULL"
    ordinalPosition: 18
    children: []
    customMetrics: []
  - name: StockKeepingUnit
    dataType: UNKNOWN
    dataLength: 180
    dataTypeDisplay: string
    description: Product SKU
    fullyQualifiedName: local_salesforce.default.salesforce.Product2.StockKeepingUnit
    tags: []
    constraint: "NULL"
    ordinalPosition: 19
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/Product2/list
domains: []
dataProducts: []
sourceHash: 65f5ed4676cb1786dd8179a3b04a3279
processedLineage: false
entityStatus: Unprocessed
