name: Product2History
fullyQualifiedName: local_salesforce.default.salesforce.Product2History
description: Product History
tableType: Regular
columns:
  - name: Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: id
    description: Product Stage ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 1
    children: []
    customMetrics: []
  - name: IsDeleted
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: boolean
    description: Deleted
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.IsDeleted
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 2
    children: []
    customMetrics: []
  - name: Product2Id
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Product ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.Product2Id
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 3
    children: []
    customMetrics: []
  - name: CreatedById
    dataType: VARCHAR
    dataLength: 18
    dataTypeDisplay: reference
    description: Created By ID
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.CreatedById
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 4
    children: []
    customMetrics: []
  - name: CreatedDate
    dataType: UNKNOWN
    dataLength: 0
    dataTypeDisplay: datetime
    description: Created Date
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.CreatedDate
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 5
    children: []
    customMetrics: []
  - name: Field
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: picklist
    description: Changed Field
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.Field
    tags: []
    constraint: NOT_NULL
    ordinalPosition: 6
    children: []
    customMetrics: []
  - name: OldValue
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: anytype
    description: Old Value
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.OldValue
    tags: []
    constraint: "NULL"
    ordinalPosition: 7
    children: []
    customMetrics: []
  - name: NewValue
    dataType: UNKNOWN
    dataLength: 255
    dataTypeDisplay: anytype
    description: New Value
    fullyQualifiedName: local_salesforce.default.salesforce.Product2History.NewValue
    tags: []
    constraint: "NULL"
    ordinalPosition: 8
    children: []
    customMetrics: []
owners: []
databaseSchema:
  id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
  type: databaseSchema
  name: salesforce
  fullyQualifiedName: local_salesforce.default.salesforce
  displayName: salesforce
  deleted: false
database:
  id: 2cedc857-dacf-4943-b02e-9f2578aaf3c6
  type: database
  name: default
  fullyQualifiedName: local_salesforce.default
  displayName: default
  deleted: false
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: deleted
      oldValue: false
      newValue: true
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://energy-fun-7814.my.salesforce.com/lightning/o/Product2History/list
domains: []
dataProducts: []
sourceHash: 11f9909ec4ca90b89f2a33afacee8aa3
processedLineage: false
entityStatus: Unprocessed
