name: default
fullyQualifiedName: testunitycatalog.main.default
dataProducts: []
owners: []
service:
  id: fd3d5144-3617-4ec5-9cdc-43b78edbe578
  type: databaseService
  name: testunitycatalog
  fullyQualifiedName: testunitycatalog
  description: ""
  displayName: testunitycatalog
  deleted: false
serviceType: UnityCatalog
database:
  id: 08447ef6-5dcc-40e6-9f63-b4eaa000d3a5
  type: database
  name: main
  fullyQualifiedName: testunitycatalog.main
  displayName: main
  deleted: false
tables: []
tags: []
domains: []
sourceHash: 0a097650d3da87bfea3f8f73a23f288a
entityStatus: Approved
