name: default
fullyQualifiedName: testUnity.main.default
dataProducts: []
owners: []
service:
  id: 686dc5da-a770-4d95-92be-34544ad38d95
  type: databaseService
  name: testUnity
  fullyQualifiedName: testUnity
  description: ""
  displayName: testUnity
  deleted: false
serviceType: UnityCatalog
database:
  id: f0b631bd-c6e0-4d31-854e-f723c7c39f29
  type: database
  name: main
  fullyQualifiedName: testUnity.main
  displayName: main
  deleted: false
tables:
  - id: c01110d3-9af0-465c-a9d0-492096dc9d11
    type: table
    name: demo_data_copy
    fullyQualifiedName: testUnity.main.default.demo_data_copy
    displayName: demo_data_copy
    deleted: false
  - id: ae791dce-014c-45f9-aab6-82ef75bf828f
    type: table
    name: diamonds
    fullyQualifiedName: testUnity.main.default.diamonds
    displayName: diamonds
    deleted: false
  - id: c92ad2b3-3239-4369-8d62-bdb3d471d263
    type: table
    name: sample_table
    fullyQualifiedName: testUnity.main.default.sample_table
    displayName: sample_table
    deleted: false
tags: []
domains: []
sourceHash: 134abf793cd8844c33926707863ac4a5
entityStatus: Approved
