name: default
fullyQualifiedName: local_salesforce1.default
dataProducts: []
tags: []
owners: []
service:
  id: e3ce395e-1c79-4c7d-8638-9110736de43d
  type: databaseService
  name: local_salesforce1
  fullyQualifiedName: local_salesforce1
  displayName: local_salesforce1
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: e5390b97-e60b-4bf5-9354-61152e8500f0
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: local_salesforce1.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: b0d89f3f1ead56db6fb358fd16ba0dad
entityStatus: Unprocessed
