name: default
fullyQualifiedName: local_salesforce2.default
dataProducts: []
tags: []
owners: []
service:
  id: dd8313e2-2c73-4f1b-9e36-bb21134505e7
  type: databaseService
  name: local_salesforce2
  fullyQualifiedName: local_salesforce2
  displayName: local_salesforce2
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: 3f4092fa-d458-45bc-9f26-54cebd5e40be
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: local_salesforce2.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: 27676a61465b4d1dc6e2f747b0aad2fb
entityStatus: Unprocessed
