name: default
fullyQualifiedName: testunitycatalog.demo.default
dataProducts: []
owners: []
service:
  id: fd3d5144-3617-4ec5-9cdc-43b78edbe578
  type: databaseService
  name: testunitycatalog
  fullyQualifiedName: testunitycatalog
  description: ""
  displayName: testunitycatalog
  deleted: false
serviceType: UnityCatalog
database:
  id: 2f3a2f0e-8b66-418a-98b9-5a9ca1c51848
  type: database
  name: demo
  fullyQualifiedName: testunitycatalog.demo
  displayName: demo
  deleted: false
tables:
  - id: 7fb0e49f-989e-428f-b054-c1ee6e4c40ef
    type: table
    name: complex_data
    fullyQualifiedName: testunitycatalog.demo.default.complex_data
    description: <description>aaa
    displayName: complex_data
    deleted: false
  - id: b9764f18-9dcf-4849-beb3-ea157485a93d
    type: table
    name: demo_data
    fullyQualifiedName: testunitycatalog.demo.default.demo_data
    description: <p>New description for table.</p>
    displayName: demo_data
    deleted: false
  - id: 76358029-ec5d-46a4-a844-ae316b503949
    type: table
    name: demo_data_ext_tbl2
    fullyQualifiedName: testunitycatalog.demo.default.demo_data_ext_tbl2
    displayName: demo_data_ext_tbl2
    deleted: false
  - id: ca5e5f84-b27f-404e-8060-9f6109861ab4
    type: table
    name: demo_data_ext_tbl3
    fullyQualifiedName: testunitycatalog.demo.default.demo_data_ext_tbl3
    displayName: demo_data_ext_tbl3
    deleted: false
  - id: 5c9b8058-0296-45c1-85cd-41581c5d2102
    type: table
    name: example_table
    fullyQualifiedName: testunitycatalog.demo.default.example_table
    displayName: example_table
    deleted: false
  - id: 477f0b32-86f9-46b7-9c12-5ab47308fb20
    type: table
    name: load_data_exp
    fullyQualifiedName: testunitycatalog.demo.default.load_data_exp
    displayName: load_data_exp
    deleted: false
  - id: 6280b87b-a0ba-4f8f-928b-e36bc828389a
    type: table
    name: new_cts
    fullyQualifiedName: testunitycatalog.demo.default.new_cts
    displayName: new_cts
    deleted: false
  - id: c9768ef6-d9ce-4c25-80d8-5a8c72b1432e
    type: table
    name: new_insert
    fullyQualifiedName: testunitycatalog.demo.default.new_insert
    displayName: new_insert
    deleted: false
  - id: f29ea6ff-992c-45fb-b6e8-b6511fb88228
    type: table
    name: test_table
    fullyQualifiedName: testunitycatalog.demo.default.test_table
    displayName: test_table
    deleted: false
tags: []
domains: []
sourceHash: 69074c304e9a70909b001f0f351a95e2
entityStatus: Approved
