name: dev
fullyQualifiedName: asd\.dev
dataProducts: []
tags: []
owners: []
service:
  id: f2326d7d-4709-46ab-9532-77a6bb236cd1
  type: databaseService
  name: asd\
  fullyQualifiedName: asd\
  displayName: asd\
  deleted: false
serviceType: Redshift
databaseSchemas:
  - id: 115cb16e-849b-4458-aa05-19d34ebde90c
    type: databaseSchema
    name: dbt_jaffle
    fullyQualifiedName: asd\.dev.dbt_jaffle
    displayName: dbt_jaffle
    deleted: false
default: false
domains: []
sourceHash: d245eefc806e58536b86192d6abb4c6d
entityStatus: Unprocessed
