name: default
fullyQualifiedName: Athena Test.default
displayName: ""
description: ""
dataProducts: []
tags:
  - tagFQN: '"Bug.Test".Newterm.dummy test term'
    name: dummy test term
    displayName: dummy test term
    description: <p>dummy test term</p>
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '"Bug.Test".TestingDraft edited'
    name: TestingDraft edited
    displayName: Testing Draft
    description: 2test demo2
    style:
      color: "#db1414"
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '"Bug.Test".dataterm'
    name: dataterm
    displayName: dataterm
    description: <p>dataterm</p>
    style: {}
    source: Glossary
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: PostgresPolicyTags.sample_policy
    name: sample_policy
    description: Postgres Tag Value
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: STAGE.production
    name: production
    description: SNOWFLAKE TAG VALUE
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: Tier.Tier1
    name: Tier1
    description: |-
      **Critical Source of Truth business data assets of an organization**

      - Used in critical metrics and dashboards to drive business and product decisions

      - Used in critical compliance reporting to regulators, govt entities, and third party

      - Used in brand or revenue impacting online user-facing experiences (search results, advertisement, promotions, and experimentation)

      - Other high impact use, such as ML models and fraud detection

      - Source used to derive other critical Tier-1 datasets
    style:
      color: "#ec1313"
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '`custom`.tag1'
    name: tag1
    displayName: tag1
    description: <p>tag1</p>
    style:
      color: "#fd3f3f"
      iconURL: https://cdn-icons-png.flaticon.com/512/9029/9029931.png
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: dbtTags.model_tag_two
    name: model_tag_two
    description: dbt Tags
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
owners:
  - id: fb8e44c9-b9c5-45bc-9691-b3343b5d5b7c
    type: user
    name: 23saints23
    fullyQualifiedName: 23saints23
    displayName: 23saints23
    deleted: false
  - id: 4614b5b7-7acc-4b93-96a5-3913903851f8
    type: user
    name: aanqueti18
    fullyQualifiedName: aanqueti18
    displayName: aanqueti18
    deleted: false
  - id: 089347d6-806c-4a27-8b95-9d101d0d3667
    type: user
    name: bethbryant
    fullyQualifiedName: bethbryant
    displayName: Aaron Alexander
    deleted: false
  - id: 02d03179-e7fb-4006-8a82-aa058a46c57e
    type: user
    name: jaimecrosby
    fullyQualifiedName: jaimecrosby
    displayName: Aaron Bradley
    deleted: false
  - id: d0107fe9-afbe-4966-914f-bfec7dfc5861
    type: user
    name: wilsondanny
    fullyQualifiedName: wilsondanny
    displayName: Aaron Baker
    deleted: false
service:
  id: c289313f-168d-43eb-8996-07b4a13c6a26
  type: databaseService
  name: Athena Test
  fullyQualifiedName: Athena Test
  description: ""
  displayName: Athena Test
  deleted: false
serviceType: Athena
databaseSchemas:
  - id: c221dfe3-6962-4017-8f26-cf7208fe63d8
    type: databaseSchema
    name: analytics
    fullyQualifiedName: Athena Test.default.analytics
    description: <p>This is test 1</p>
    displayName: Analytics
    deleted: false
  - id: ec39d618-f154-4eb7-8639-73551dc781f7
    type: databaseSchema
    name: default
    fullyQualifiedName: Athena Test.default.default
    description: <p>This is test 2</p>
    displayName: Default
    deleted: false
  - id: 8952212b-e24f-4e0b-962d-107d96bcc5be
    type: databaseSchema
    name: dev
    fullyQualifiedName: Athena Test.default.dev
    description: <p>This is test 3</p>
    displayName: Dev
    deleted: false
  - id: 19a2b144-93a9-496a-8aa1-439020b11345
    type: databaseSchema
    name: e2e_db
    fullyQualifiedName: Athena Test.default.e2e_db
    description: ""
    displayName: e2e_db
    deleted: false
  - id: fa11fa82-63d8-4253-9352-38faf1183deb
    type: databaseSchema
    name: mydatabase
    fullyQualifiedName: Athena Test.default.mydatabase
    description: ""
    displayName: mydatabase
    deleted: false
  - id: 0d31a63e-fe0b-4b3f-9f37-da9d73f22a4f
    type: databaseSchema
    name: raw-zone
    fullyQualifiedName: Athena Test.default.raw-zone
    description: ""
    displayName: raw-zone
    deleted: false
  - id: 786d11e9-6b15-43cb-bd0a-b8bb5987d0d7
    type: databaseSchema
    name: test_db
    fullyQualifiedName: Athena Test.default.test_db
    description: ""
    displayName: test_db
    deleted: false
  - id: 417f8dbe-0195-45af-9ace-5c7050542f53
    type: databaseSchema
    name: testdatalake_db
    fullyQualifiedName: Athena Test.default.testdatalake_db
    description: ""
    displayName: testdatalake_db
    deleted: false
  - id: c967be94-2d42-4257-9c9b-fe592ade32d1
    type: databaseSchema
    name: zipcode-db
    fullyQualifiedName: Athena Test.default.zipcode-db
    description: ""
    displayName: zipcode-db
    deleted: false
incrementalChangeDescription:
  fieldsAdded:
    - name: extension
      newValue: "[{\"databaseId\":2}]"
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.2
  changeSummary: {}
default: false
extension:
  databaseId: 2
domains:
  - id: 9b777e79-3556-4eff-b9e9-bb71037b8dd0
    type: domain
    name: TestHarsha2
    fullyQualifiedName: TestHarsha.TestHarsha2
    description: <p>TestHarsha</p>
    displayName: TestHarsha2
sourceHash: ce424b464673a13b8c7435b3779a3634
entityStatus: Approved
