domainType: Consumer-aligned
name: Product
fullyQualifiedName: Product
displayName: Product Name
description: A Domain producing  and serving Product Master Data.
style:
  color: "#0968da"
children: []
childrenCount: 0
owners: []
experts: []
tags: []
