name: default
fullyQualifiedName: local_salesforce.default
dataProducts: []
tags: []
owners: []
service:
  id: dd198fe7-cd27-446a-9713-452aa257669c
  type: databaseService
  name: local_salesforce
  fullyQualifiedName: local_salesforce
  displayName: local_salesforce
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: 9bda545c-bf37-4c29-b63e-07cabc2b1926
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: local_salesforce.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: 7d004ef07d9572a42734f9d2af174901
entityStatus: Unprocessed
