name: default
fullyQualifiedName: dbx - keshav.demo.default
description: Default schema (auto-created)
dataProducts: []
owners: []
service:
  id: 0cda8939-ffbd-4f42-8c1b-29552ea53c0f
  type: databaseService
  name: dbx - keshav
  fullyQualifiedName: dbx - keshav
  description: ""
  displayName: dbx - keshav
  deleted: false
serviceType: Databricks
database:
  id: cd17a1de-b8f6-4b2b-b7d3-046376580f00
  type: database
  name: demo
  fullyQualifiedName: dbx - keshav.demo
  displayName: demo
  deleted: false
tables:
  - id: 93665974-4de9-41ef-aff5-b80fbf6af1b2
    type: table
    name: complex_data
    fullyQualifiedName: dbx - keshav.demo.default.complex_data
    description: <description>aaa
    displayName: complex_data
    deleted: false
  - id: dfb69ecd-007d-49d9-ba47-ff020aaecb0d
    type: table
    name: demo_data
    fullyQualifiedName: dbx - keshav.demo.default.demo_data
    description: <p>New description for table.</p>
    displayName: demo_data
    deleted: false
  - id: 054cfb3b-aabf-4df6-9963-9fdf66c278b3
    type: table
    name: demo_data_ext_tbl2
    fullyQualifiedName: dbx - keshav.demo.default.demo_data_ext_tbl2
    description: reverse metadata test description
    displayName: demo_data_ext_tbl2
    deleted: false
  - id: a7b35a0a-9519-461c-a244-2364f8319d79
    type: table
    name: demo_data_ext_tbl3
    fullyQualifiedName: dbx - keshav.demo.default.demo_data_ext_tbl3
    displayName: demo_data_ext_tbl3
    deleted: false
  - id: deb2d136-3dc8-4b83-ae04-f9212196ac15
    type: table
    name: demo_sales_location_external_location_table
    fullyQualifiedName: dbx - keshav.demo.default.demo_sales_location_external_location_table
    displayName: demo_sales_location_external_location_table
    deleted: false
  - id: d50f7a00-ecdb-48bf-9d26-3f9b2d5f91d6
    type: table
    name: demo_sales_location_table
    fullyQualifiedName: dbx - keshav.demo.default.demo_sales_location_table
    description: Created by the file upload UI
    displayName: demo_sales_location_table
    deleted: false
  - id: be0cbe00-4e3a-430a-a3f0-1272502ff575
    type: table
    name: demo_sales_location_table2
    fullyQualifiedName: dbx - keshav.demo.default.demo_sales_location_table2
    displayName: demo_sales_location_table2
    deleted: false
  - id: 848bbb44-dca6-4e71-abb7-fb04bf791b33
    type: table
    name: demo_sales_processed
    fullyQualifiedName: dbx - keshav.demo.default.demo_sales_processed
    displayName: demo_sales_processed
    deleted: false
  - id: 897c6734-d412-4f81-aa53-706bc84ed365
    type: table
    name: employee_details
    fullyQualifiedName: dbx - keshav.demo.default.employee_details
    displayName: employee_details
    deleted: false
  - id: 44a09222-2e63-4e79-b312-542a5310fdde
    type: table
    name: employee_details2
    fullyQualifiedName: dbx - keshav.demo.default.employee_details2
    displayName: employee_details2
    deleted: false
  - id: 9e63fd41-ac99-4453-843d-e4043749e44d
    type: table
    name: example_table
    fullyQualifiedName: dbx - keshav.demo.default.example_table
    displayName: example_table
    deleted: false
  - id: c000d409-8041-40e5-9a9a-8dad99616cdd
    type: table
    name: insurance_struct
    fullyQualifiedName: dbx - keshav.demo.default.insurance_struct
    displayName: insurance_struct
    deleted: false
  - id: 358a2c75-3902-4d5e-8942-4c4122d796ca
    type: table
    name: load_data_exp
    fullyQualifiedName: dbx - keshav.demo.default.load_data_exp
    displayName: load_data_exp
    deleted: false
  - id: 6556d0c8-ae51-4a67-bed7-df324e2aa423
    type: table
    name: mynewtable_testing_lineage
    fullyQualifiedName: dbx - keshav.demo.default.mynewtable_testing_lineage
    displayName: mynewtable_testing_lineage
    deleted: false
  - id: 5e387dbf-e158-4ea5-87ef-d7ffb2e32fc6
    type: table
    name: new_cts
    fullyQualifiedName: dbx - keshav.demo.default.new_cts
    displayName: new_cts
    deleted: false
  - id: 4016796e-6c48-42fe-95d1-a8e8b66d537b
    type: table
    name: new_insert
    fullyQualifiedName: dbx - keshav.demo.default.new_insert
    displayName: new_insert
    deleted: false
  - id: 871aea88-b372-43d6-bccd-956355c86b67
    type: table
    name: tabletestkeshav2
    fullyQualifiedName: dbx - keshav.demo.default.tabletestkeshav2
    displayName: tabletestkeshav2
    deleted: false
  - id: b3566813-5830-4958-899e-4aa999c68169
    type: table
    name: test_table
    fullyQualifiedName: dbx - keshav.demo.default.test_table
    displayName: test_table
    deleted: false
  - id: c6cdf5b6-f33c-4336-9ed9-d95692a60139
    type: table
    name: testkeshav
    fullyQualifiedName: dbx - keshav.demo.default.testkeshav
    description: Created by the file upload UI
    displayName: testkeshav
    deleted: false
tags:
  - tagFQN: beedd.sdaaaaa
    name: sdaaaaa
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: catalog_tags.catalog_TAGS
    name: catalog_TAGS
    displayName: Bronze_medal
    description: DATABRICKS TAG
    style:
      color: "#C08329"
      iconURL: BronzeCertification.svg
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: color.green
    name: green
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: none.NONE
    name: NONE
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: nrp.NRP
    name: NRP
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: personal.Personal
    name: Personal
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: testing.NONE
    name: NONE
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: xyz.xyz
    name: xyz
    description: DATABRICKS TAG
    source: Classification
    labelType: Automated
    state: Suggested
    appliedAt: 1767969396000
    appliedBy: admin
domains: []
sourceHash: 853a6048e6bcf58b2f8dbe288feb2bda
entityStatus: Unprocessed
