name: production
fullyQualifiedName: testUnity.postgres_catalog.production
dataProducts: []
owners: []
service:
  id: 686dc5da-a770-4d95-92be-34544ad38d95
  type: databaseService
  name: testUnity
  fullyQualifiedName: testUnity
  description: ""
  displayName: testUnity
  deleted: false
serviceType: UnityCatalog
database:
  id: 631ee5ac-ca75-4695-9cb0-9c82bd02a746
  type: database
  name: postgres_catalog
  fullyQualifiedName: testUnity.postgres_catalog
  displayName: postgres_catalog
  deleted: false
tables:
  - id: f932bb9a-4005-4040-a99a-280a1b62c7d3
    type: table
    name: _airbyte_raw_brands
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_brands
    displayName: _airbyte_raw_brands
    deleted: false
  - id: f110f96e-9c86-4923-b00c-5b20ea597569
    type: table
    name: _airbyte_raw_categories
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_categories
    displayName: _airbyte_raw_categories
    deleted: false
  - id: 5e6f2eb5-58d7-46a8-9e1d-6c967e50267a
    type: table
    name: _airbyte_raw_new_cts_test
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_new_cts_test
    displayName: _airbyte_raw_new_cts_test
    deleted: false
  - id: b93d4493-b4e2-423b-b834-6cdd12a6f9d9
    type: table
    name: _airbyte_raw_new_view_test
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_new_view_test
    displayName: _airbyte_raw_new_view_test
    deleted: false
  - id: bac5f3a2-74da-4990-b514-d142bc7f3305
    type: table
    name: _airbyte_raw_products
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_products
    displayName: _airbyte_raw_products
    deleted: false
  - id: ea433b8b-54f9-451d-b197-555767b1ce80
    type: table
    name: _airbyte_raw_stocks
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_stocks
    displayName: _airbyte_raw_stocks
    deleted: false
  - id: 6bcd7b2b-0994-43b0-99c5-c64593b5b296
    type: table
    name: _airbyte_raw_test_cts_2
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_test_cts_2
    displayName: _airbyte_raw_test_cts_2
    deleted: false
  - id: 009cbee5-918c-4b69-b30d-9c41f10c9cc4
    type: table
    name: _airbyte_raw_test_cts_3
    fullyQualifiedName: testUnity.postgres_catalog.production._airbyte_raw_test_cts_3
    displayName: _airbyte_raw_test_cts_3
    deleted: false
  - id: 0a665b78-82a4-4ce1-8664-1e73b385cb89
    type: table
    name: brands
    fullyQualifiedName: testUnity.postgres_catalog.production.brands
    displayName: brands
    deleted: false
  - id: 344319ab-6173-488c-953a-0257f617d5fc
    type: table
    name: categories
    fullyQualifiedName: testUnity.postgres_catalog.production.categories
    displayName: categories
    deleted: false
  - id: dd8207cf-8942-49ef-bd4d-8e7cffacbaff
    type: table
    name: new_cts_test
    fullyQualifiedName: testUnity.postgres_catalog.production.new_cts_test
    displayName: new_cts_test
    deleted: false
  - id: 55be54bc-36d5-4ec0-80af-0199d84251f5
    type: table
    name: new_view_test
    fullyQualifiedName: testUnity.postgres_catalog.production.new_view_test
    displayName: new_view_test
    deleted: false
  - id: c7738725-f5d6-4c4c-bbde-01ce5b5b6dfe
    type: table
    name: products
    fullyQualifiedName: testUnity.postgres_catalog.production.products
    displayName: products
    deleted: false
  - id: 1bff7878-c0ed-4323-b6bc-a5b050e53f5d
    type: table
    name: stocks
    fullyQualifiedName: testUnity.postgres_catalog.production.stocks
    displayName: stocks
    deleted: false
  - id: 02a59549-eedd-42df-a67e-6a47a9acbb3b
    type: table
    name: test_cts_2
    fullyQualifiedName: testUnity.postgres_catalog.production.test_cts_2
    displayName: test_cts_2
    deleted: false
  - id: 6a6e3f4d-9edc-4a25-8926-3f0c007cacd7
    type: table
    name: test_cts_3
    fullyQualifiedName: testUnity.postgres_catalog.production.test_cts_3
    displayName: test_cts_3
    deleted: false
tags: []
domains: []
sourceHash: 9a60f991b288489f86b9de07414dd9b8
entityStatus: Approved
