name: default
fullyQualifiedName: Hybrid test mysql 2 - gyo 2025-04-22.default
dataProducts: []
tags: []
owners: []
service:
  id: e3707074-f3c7-4c1c-ac8f-1cf83ab51300
  type: databaseService
  name: Hybrid test mysql 2 - gyo 2025-04-22
  fullyQualifiedName: Hybrid test mysql 2 - gyo 2025-04-22
  description: ""
  displayName: Hybrid test mysql 2 - gyo 2025-04-22
  deleted: false
serviceType: Mysql
databaseSchemas:
  - id: bd966a9f-0ea2-4cfd-b34a-1e2b53329dea
    type: databaseSchema
    name: cypress_integrations_test_db
    fullyQualifiedName: Hybrid test mysql 2 - gyo 2025-04-22.default.cypress_integrations_test_db
    displayName: cypress_integrations_test_db
    deleted: false
default: false
domains: []
sourceHash: 4b824ef9d557efa57cf3474ddac24e9b
entityStatus: Approved
