name: default
fullyQualifiedName: large_file_datalake_local5.default
dataProducts: []
tags: []
owners: []
service:
  id: 2e0873df-fda9-45dd-a25b-a99e1076625c
  type: databaseService
  name: large_file_datalake_local5
  fullyQualifiedName: large_file_datalake_local5
  displayName: large_file_datalake_local5
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 4d4bca9d-a9d4-43fa-9983-1e2e31d50bcb
    type: databaseSchema
    name: partitioned-data-container
    fullyQualifiedName: large_file_datalake_local5.default.partitioned-data-container
    displayName: partitioned-data-container
    deleted: false
default: false
domains: []
sourceHash: ad2d9675ea6e53984df0a27db522669a
entityStatus: Unprocessed
