name: default
fullyQualifiedName: local_salesforce4.default
dataProducts: []
tags: []
owners: []
service:
  id: 4ab1469d-fda8-432f-832c-e9bd40fdc251
  type: databaseService
  name: local_salesforce4
  fullyQualifiedName: local_salesforce4
  displayName: local_salesforce4
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: 565fc88c-c20e-4bb5-92a5-97a317c9775e
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: local_salesforce4.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: 6a62c2545ff28b7f9cb248a0b1fb804a
entityStatus: Unprocessed
