name: default
fullyQualifiedName: local_salesforce3.default
dataProducts: []
tags: []
owners: []
service:
  id: a0804653-7c74-4e57-9c85-d8c8e5c2f569
  type: databaseService
  name: local_salesforce3
  fullyQualifiedName: local_salesforce3
  displayName: local_salesforce3
  deleted: false
serviceType: Salesforce
databaseSchemas:
  - id: 6a570a74-c606-4f56-bb7f-2435f3bc6b71
    type: databaseSchema
    name: salesforce
    fullyQualifiedName: local_salesforce3.default.salesforce
    displayName: salesforce
    deleted: false
default: false
domains: []
sourceHash: d1ce4bffedc0121a51a08ed87b22b004
entityStatus: Unprocessed
