name: default
fullyQualifiedName: athena_prod.default
displayName: default_display_name
description: ""
dataProducts: []
tags:
  - tagFQN: Tier.Tier1
    name: Tier1
    description: |-
      **Critical Source of Truth business data assets of an organization**

      - Used in critical metrics and dashboards to drive business and product decisions

      - Used in critical compliance reporting to regulators, govt entities, and third party

      - Used in brand or revenue impacting online user-facing experiences (search results, advertisement, promotions, and experimentation)

      - Other high impact use, such as ML models and fraud detection

      - Source used to derive other critical Tier-1 datasets
    style:
      color: "#ec1313"
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: '`custom`.tag1'
    name: tag1
    displayName: tag1
    description: <p>tag1</p>
    style:
      color: "#fd3f3f"
      iconURL: https://cdn-icons-png.flaticon.com/512/9029/9029931.png
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
  - tagFQN: advanceSearch.search_part_2
    name: search_part_2
    displayName: ""
    description: this is search_part_2
    style: {}
    source: Classification
    labelType: Manual
    state: Confirmed
    appliedAt: 1767969396000
    appliedBy: admin
owners:
  - id: 9cd9a536-ab77-4d73-bb65-cc71ed8a85ac
    type: user
    name: sachin
    fullyQualifiedName: sachin
    displayName: Sachin Chaurasiya
    deleted: false
service:
  id: 27eb56a8-103c-4879-b1b5-0fdd71b02b82
  type: databaseService
  name: athena_prod
  fullyQualifiedName: athena_prod
  description: ""
  displayName: athena_prod_display_name
  deleted: false
serviceType: Athena
databaseSchemas:
  - id: 8964b4e4-1534-427c-9080-4dc97a5bbe7a
    type: databaseSchema
    name: default
    fullyQualifiedName: athena_prod.default.default
    description: <p>test update description test</p>
    displayName: default
    deleted: false
  - id: 0ec65dfe-075b-4df0-8504-3eae3b6f77c0
    type: databaseSchema
    name: mydatabase
    fullyQualifiedName: athena_prod.default.mydatabase
    description: ""
    displayName: mydatabase
    deleted: false
  - id: ab0f82ed-6d58-45a9-b4e2-d94f668fba87
    type: databaseSchema
    name: newschema
    fullyQualifiedName: athena_prod.default.newschema
    description: Some description here updated
    displayName: New Schema1
    deleted: false
  - id: 76a27435-9cac-429f-853f-83e32da4d916
    type: databaseSchema
    name: raw-zone
    fullyQualifiedName: athena_prod.default.raw-zone
    description: ""
    displayName: raw-zone
    deleted: false
  - id: 89b24c0f-9f94-484d-8406-1068231a698b
    type: databaseSchema
    name: testdatalake_db
    fullyQualifiedName: athena_prod.default.testdatalake_db
    description: ""
    displayName: testdatalake_db
    deleted: false
  - id: 775f7729-4df1-4369-a8b5-a41e8c78c480
    type: databaseSchema
    name: zipcode-db
    fullyQualifiedName: athena_prod.default.zipcode-db
    description: "<p>description testing s simply dummy text of the printing and typesetting\
      \ industry. Lorem Ipsum has been the industry's standard dummy text ever since\
      \ the 1500s, when an unknown printer took a galley of type and scrambled it\
      \ to make a type specimen book. It has survived not only five centuries, but\
      \ also the leap into electronic typesetting, remaining essentially unchanged.\
      \ It was popularised in the 1960s with the release of Letraset sheets containing\
      \ Lorem Ipsum passages, and more recently with desktop publishing software like\
      \ Aldus PageMaker including versions of Lorem Ipsum.<br>s simply dummy text\
      \ of the printing and typesetting industry. Lorem Ipsum has been the industry's\
      \ standard dummy text ever since the 1500s, when an unknown printer took a galley\
      \ of type and scrambled it to make a type specimen book. It has survived not\
      \ only five centuries, but also the leap into electronic typesetting, remaining\
      \ essentially unchanged. It was popularised in the 1960s with the release of\
      \ Letraset sheets containing Lorem Ipsum passages, and more recently with desktop\
      \ publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>"
    displayName: zipcode-db
    deleted: false
default: false
domains:
  - id: 52fc9c67-78b7-42bf-8147-69278853c230
    type: domain
    name: Design
    fullyQualifiedName: Design
    description: <p>Here' the description for Product Design</p>
    displayName: 'Product Design '
    inherited: true
entityStatus: Approved
