name: LOCAL
fullyQualifiedName: TestSnowflake.SNOWFLAKE.LOCAL
dataProducts: []
owners: []
service:
  id: a4689545-b7ad-45ec-8dde-04829253cfa8
  type: databaseService
  name: TestSnowflake
  fullyQualifiedName: TestSnowflake
  description: ""
  displayName: TestSnowflake
  deleted: false
serviceType: Snowflake
database:
  id: c1a82122-16c9-4db0-9a25-20d3b6ddfb3c
  type: database
  name: SNOWFLAKE
  fullyQualifiedName: TestSnowflake.SNOWFLAKE
  displayName: SNOWFLAKE
  deleted: false
tables: []
tags: []
sourceUrl: https://app.snowflake.com/niughrx/xi67120/#/data/databases/LOCAL
domains: []
sourceHash: 545ebcbd0111ebe763186aa2969ad202
entityStatus: Approved
