name: product_inventory
fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test.product_inventory
tableType: Regular
columns:
  - name: inventory_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test.product_inventory.inventory_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test.product_inventory.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: quantity
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test.product_inventory.quantity
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: warehouse
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test.product_inventory.warehouse
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 7a01da54-bf07-47c4-90b3-35a5921a1fa9
  type: databaseSchema
  name: hk_test
  fullyQualifiedName: bigquery 111.modified-leaf-330420.hk_test
  description: ""
  displayName: hk_test
  deleted: false
database:
  id: fb3a207a-4029-4635-817c-ad4bc5251bc7
  type: database
  name: modified-leaf-330420
  fullyQualifiedName: bigquery 111.modified-leaf-330420
  displayName: modified-leaf-330420
  deleted: false
service:
  id: c721902a-455f-433b-8bdc-958e82710043
  type: databaseService
  name: bigquery 111
  fullyQualifiedName: bigquery 111
  description: ""
  displayName: bigquery 111
  deleted: false
serviceType: BigQuery
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated: []
  fieldsDeleted: []
  previousVersion: 0.1
sourceUrl: https://console.cloud.google.com/bigquery?project=modified-leaf-330420&ws=!1m5!1m4!4m3!1smodified-leaf-330420!2shk_test!3sproduct_inventory
domains: []
dataProducts: []
lifeCycle:
  created:
    timestamp: 1763667175907
sourceHash: 64ef6dc9823338487146e8d926dc7992
processedLineage: false
entityStatus: Unprocessed
