name: default
fullyQualifiedName: DatalakeAzureAuthTest.default
dataProducts: []
tags: []
owners: []
service:
  id: 4ce97071-742d-42f1-bd74-f779b17970cf
  type: databaseService
  name: DatalakeAzureAuthTest
  fullyQualifiedName: DatalakeAzureAuthTest
  description: ""
  displayName: DatalakeAzureAuthTest
  deleted: false
serviceType: Datalake
databaseSchemas:
  - id: 81e5f273-f132-4b0a-938a-744c41f7466e
    type: databaseSchema
    name: ingestion
    fullyQualifiedName: DatalakeAzureAuthTest.default.ingestion
    displayName: ingestion
    deleted: false
default: false
domains: []
sourceHash: 2a99133696283c7ef4720d9383589d19
entityStatus: Approved
