name: products
fullyQualifiedName: dbx - keshav.demo.uniform_schema.products
tableType: Regular
columns:
  - name: product_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.product_name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_description
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.product_description
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: category
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.category
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: price
    dataType: DECIMAL
    dataLength: 1
    dataTypeDisplay: "decimal(10,2)"
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.price
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: inventory_sku
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.inventory_sku
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: is_active
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.is_active
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: created_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.created_at
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: updated_at
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp
    fullyQualifiedName: dbx - keshav.demo.uniform_schema.products.updated_at
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners:
  - id: 1b72b315-222e-41ec-9763-30125a1fdabc
    type: user
    name: suman
    fullyQualifiedName: suman
    displayName: suman
    deleted: false
databaseSchema:
  id: 44eb96a5-3770-488f-9aae-7a4df8401aeb
  type: databaseSchema
  name: uniform_schema
  fullyQualifiedName: dbx - keshav.demo.uniform_schema
  description: uniform schema demo
  displayName: uniform_schema
  deleted: false
database:
  id: cd17a1de-b8f6-4b2b-b7d3-046376580f00
  type: database
  name: demo
  fullyQualifiedName: dbx - keshav.demo
  displayName: demo
  deleted: false
service:
  id: 0cda8939-ffbd-4f42-8c1b-29552ea53c0f
  type: databaseService
  name: dbx - keshav
  fullyQualifiedName: dbx - keshav
  description: ""
  displayName: dbx - keshav
  deleted: false
serviceType: Databricks
locationPath: s3://awsdatalake-testing/databricks-new-metastore/3849887a-24ae-4b8e-a470-9d953589f80e/tables/4f7c9225-c024-4feb-a1cd-295c7266e93e
tags: []
joins:
  startDate: 2026-01-07
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: ada4de55c4a1e564f12029316b20d21d
processedLineage: false
entityStatus: Unprocessed
